// Process issue workflow script.
// Called by .github/workflows/process-issue.yml via actions/github-script.
// Receives { github, context } from the workflow.
//
// Handles patch-format issues generated by the contribution wizard.
// Create issues contain full YAML in a ```yaml code block.
// Update issues contain a unified diff in a ```diff code block.

const YAML = require("yaml");
const {
    extractPatchMeta,
    extractYamlBlock,
    extractDiffBlock,
    extractTreeParent,
    readGenusFile,
    readFileContent,
    createPR,
    createMultiFilePR,
    applyPatch,
    commentError,
    serializeYaml,
} = require("./helpers.cjs");

/**
 * Entry point — extracts patch metadata from the issue body and routes
 * to the appropriate handler based on the action and content format.
 *
 * @param {object} options
 * @param {object} options.github - Octokit instance from actions/github-script.
 * @param {object} options.context - GitHub Actions event context.
 */
module.exports = async function ({ github, context })
{
    const body = context.payload.issue.body;
    const issueNumber = context.payload.issue.number;
    const issueAuthor = context.payload.issue.user.login;
    const repo = context.repo;

    const meta = extractPatchMeta(body);

    if (!meta)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not find patch metadata in the issue body. This issue may not have been created by the contribution wizard.",
            "Needs More Information",
        );

        return;
    }

    if (meta.action === "create")
    {
        await handleCreateFromYaml({ github, repo, issueNumber, issueAuthor, meta, body });
    }
    else if (meta.action === "update")
    {
        const diffContent = extractDiffBlock(body);

        if (diffContent)
        {
            await handleDiffUpdate({ github, repo, issueNumber, issueAuthor, meta, diffContent });
        }
        else
        {
            // Backward compatibility: older issues may use full YAML for updates
            await handleYamlUpdate({ github, repo, issueNumber, issueAuthor, meta, body });
        }
    }
    else if (meta.action === "create-clade")
    {
        await handleCreateClade({ github, repo, issueNumber, issueAuthor, meta, body });
    }
    else
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Unknown action: "${meta.action}". Expected "create", "update", or "create-clade".`,
            "Needs More Information",
        );
    }
};

/**
 * Validates parsed YAML for required fields and path consistency.
 *
 * @param {object} parsed - The parsed YAML object.
 * @param {string} expectedPath - The expected file path from metadata.
 * @returns {{ valid: boolean, error: string | null }} Validation result.
 */
function validateParsedYaml(parsed, expectedPath)
{
    if (!parsed || !parsed.genus)
    {
        return { valid: false, error: "The YAML content is missing a required 'genus' field." };
    }

    if (parsed.species && !Array.isArray(parsed.species))
    {
        return { valid: false, error: "The 'species' field must be an array." };
    }

    const genusName = parsed.genus;
    const computedPath = `genera/${genusName.charAt(0).toUpperCase()}/${genusName}.yml`;

    if (expectedPath !== computedPath)
    {
        return { valid: false, error: `File path mismatch: expected "${computedPath}" but got "${expectedPath}".` };
    }

    return { valid: true, error: null };
}

/**
 * Handles a "create" action — extracts YAML from the issue body and
 * creates a new genus file.
 *
 * @param {object} options
 * @param {object} options.github - Octokit instance.
 * @param {{ owner: string, repo: string }} options.repo - Repository coordinates.
 * @param {number} options.issueNumber - Originating issue number.
 * @param {string} options.issueAuthor - GitHub login of the issue author.
 * @param {{ path: string, action: string }} options.meta - Extracted patch metadata.
 * @param {string} options.body - The raw issue body.
 */
async function handleCreateFromYaml({ github, repo, issueNumber, issueAuthor, meta, body })
{
    const yamlContent = extractYamlBlock(body);

    if (!yamlContent)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not find a YAML code block in the issue body.",
            "Needs More Information",
        );

        return;
    }

    let parsed;

    try
    {
        parsed = YAML.parse(yamlContent);
    }
    catch (parseError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Failed to parse YAML: ${parseError.message}`,
            "Needs More Information",
        );
        return;
    }

    const validation = validateParsedYaml(parsed, meta.path);

    if (!validation.valid)
    {
        await commentError(github, repo, issueNumber, validation.error, "Needs More Information");
        return;
    }

    const genusName = parsed.genus;
    const existing = await readGenusFile(github, repo, genusName);

    if (existing)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `"${genusName}" already exists in the dataset. Use the Update Genus flow instead.`,
        );

        return;
    }

    const serializedYaml = serializeYaml(parsed);

    await createPR({
        github,
        repo,
        issueNumber,
        issueAuthor,
        filePath: meta.path,
        yamlContent: serializedYaml,
        branchName: `genus/${genusName.toLowerCase()}`,
        prTitle: `Add genus: ${genusName}`,
        prBody: `Adds ${genusName} to the dataset.`,
    });
}

/**
 * Handles an "update" action using a unified diff patch. Reads the
 * existing file, applies the patch, validates the result, and creates a PR.
 *
 * @param {object} options
 * @param {object} options.github - Octokit instance.
 * @param {{ owner: string, repo: string }} options.repo - Repository coordinates.
 * @param {number} options.issueNumber - Originating issue number.
 * @param {string} options.issueAuthor - GitHub login of the issue author.
 * @param {{ path: string, action: string }} options.meta - Extracted patch metadata.
 * @param {string} options.diffContent - The unified diff content.
 */
async function handleDiffUpdate({ github, repo, issueNumber, issueAuthor, meta, diffContent })
{
    // Extract genus name from the file path
    const pathParts = meta.path.match(/genera\/[A-Z]\/(.+)\.yml$/);

    if (!pathParts)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Invalid file path format: "${meta.path}".`,
            "Needs More Information",
        );

        return;
    }

    const genusName = pathParts[1];
    const existing = await readGenusFile(github, repo, genusName);

    if (!existing)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Genus file not found: ${meta.path}`,
        );

        return;
    }

    // Normalize the existing content through serializeYaml() so its formatting
    // matches the wizard's serialization (which produced the diff).
    const normalizedContent = serializeYaml(existing.data);

    let patchedContent;

    try
    {
        patchedContent = applyPatch(normalizedContent, diffContent);
    }
    catch (patchError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Patch could not be applied: ${patchError.message} Please try again with the latest data.`,
            "Needs More Information",
        );

        return;
    }

    let parsed;

    try
    {
        parsed = YAML.parse(patchedContent);
    }
    catch (parseError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Patched YAML is invalid: ${parseError.message}`,
            "Needs More Information",
        );

        return;
    }

    const validation = validateParsedYaml(parsed, meta.path);

    if (!validation.valid)
    {
        await commentError(github, repo, issueNumber, validation.error, "Needs More Information");
        return;
    }

    const serializedYaml = serializeYaml(parsed);

    await createPR({
        github,
        repo,
        issueNumber,
        issueAuthor,
        filePath: meta.path,
        fileSha: existing.sha,
        yamlContent: serializedYaml,
        branchName: `update/${genusName.toLowerCase()}-${issueNumber}`,
        prTitle: `Update ${genusName}`,
        prBody: `Updates ${genusName} in the dataset.`,
    });
}

/**
 * Handles an "update" action using a full YAML block (backward
 * compatibility with issues created before the diff-based format).
 *
 * @param {object} options
 * @param {object} options.github - Octokit instance.
 * @param {{ owner: string, repo: string }} options.repo - Repository coordinates.
 * @param {number} options.issueNumber - Originating issue number.
 * @param {string} options.issueAuthor - GitHub login of the issue author.
 * @param {{ path: string, action: string }} options.meta - Extracted patch metadata.
 * @param {string} options.body - The raw issue body.
 */
async function handleYamlUpdate({ github, repo, issueNumber, issueAuthor, meta, body })
{
    const yamlContent = extractYamlBlock(body);

    if (!yamlContent)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not find a YAML or diff code block in the issue body.",
            "Needs More Information",
        );

        return;
    }

    let parsed;

    try
    {
        parsed = YAML.parse(yamlContent);
    }
    catch (parseError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Failed to parse YAML: ${parseError.message}`,
            "Needs More Information",
        );

        return;
    }

    const validation = validateParsedYaml(parsed, meta.path);

    if (!validation.valid)
    {
        await commentError(github, repo, issueNumber, validation.error, "Needs More Information");
        return;
    }

    const genusName = parsed.genus;
    const existing = await readGenusFile(github, repo, genusName);

    if (!existing)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Genus file not found: ${meta.path}`,
        );

        return;
    }

    const serializedYaml = serializeYaml(parsed);

    await createPR({
        github,
        repo,
        issueNumber,
        issueAuthor,
        filePath: meta.path,
        fileSha: existing.sha,
        yamlContent: serializedYaml,
        branchName: `update/${genusName.toLowerCase()}-${issueNumber}`,
        prTitle: `Update ${genusName}`,
        prBody: `Updates ${genusName} in the dataset.`,
    });
}

/**
 * Recursively searches for a key in a nested tree object and adds
 * a new child key under it with an empty object value.
 *
 * @param {object} node - The current tree node.
 * @param {string} parentKey - The key to find.
 * @param {string} childKey - The key to insert as a child.
 * @returns {boolean} True if the parent was found and the child inserted.
 */
function insertIntoTree(node, parentKey, childKey)
{
    for (const [key, children] of Object.entries(node))
    {
        if (key === parentKey)
        {
            if (!children || typeof children !== "object")
            {
                node[key] = {};
            }

            node[key][childKey] = {};

            return true;
        }

        if (children && typeof children === "object")
        {
            if (insertIntoTree(children, parentKey, childKey))
            {
                return true;
            }
        }
    }

    return false;
}

/**
 * Handles a "create-clade" action — extracts clade YAML from the
 * issue body, inserts the new clade into tree.yml, and creates a
 * clade definition file.
 *
 * @param {object} options
 * @param {object} options.github - Octokit instance.
 * @param {{ owner: string, repo: string }} options.repo - Repository coordinates.
 * @param {number} options.issueNumber - Originating issue number.
 * @param {string} options.issueAuthor - GitHub login of the issue author.
 * @param {{ path: string, action: string }} options.meta - Extracted patch metadata.
 * @param {string} options.body - The raw issue body.
 */
async function handleCreateClade({ github, repo, issueNumber, issueAuthor, meta, body })
{
    const treeParent = extractTreeParent(body);

    if (!treeParent)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not find tree-parent metadata in the issue body.",
            "Needs More Information",
        );

        return;
    }

    const yamlContent = extractYamlBlock(body);

    if (!yamlContent)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not find a YAML code block in the issue body.",
            "Needs More Information",
        );

        return;
    }

    let parsed;

    try
    {
        parsed = YAML.parse(yamlContent);
    }
    catch (parseError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Failed to parse YAML: ${parseError.message}`,
            "Needs More Information",
        );

        return;
    }

    if (!parsed || !parsed.clade)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "The YAML content is missing a required 'clade' field.",
            "Needs More Information",
        );

        return;
    }

    const cladeName = parsed.clade;
    const expectedPath = `clades/${cladeName}.yml`;

    if (meta.path !== expectedPath)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `File path mismatch: expected "${expectedPath}" but got "${meta.path}".`,
            "Needs More Information",
        );

        return;
    }

    // Check that the clade file doesn't already exist
    const existingClade = await readFileContent(github, repo, expectedPath);

    if (existingClade)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Clade file "${expectedPath}" already exists.`,
        );

        return;
    }

    // Read and modify tree.yml
    const treeFile = await readFileContent(github, repo, "tree.yml");

    if (!treeFile)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            "Could not read tree.yml from the repository.",
            "Needs More Information",
        );

        return;
    }

    let tree;

    try
    {
        tree = YAML.parse(treeFile.content);
    }
    catch (parseError)
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Failed to parse tree.yml: ${parseError.message}`,
            "Needs More Information",
        );

        return;
    }

    if (!insertIntoTree(tree, treeParent, cladeName))
    {
        await commentError(
            github,
            repo,
            issueNumber,
            `Parent clade "${treeParent}" not found in tree.yml.`,
            "Needs More Information",
        );

        return;
    }

    // Serialize tree — use lineWidth: 0 to prevent wrapping of the nested structure
    const treeDocument = new YAML.Document(tree);
    const treeYaml = treeDocument.toString({ lineWidth: 0 });

    const cladeYaml = serializeYaml(parsed);

    await createMultiFilePR({
        github,
        repo,
        issueNumber,
        issueAuthor,
        files: [
            { path: "tree.yml", content: treeYaml },
            { path: expectedPath, content: cladeYaml },
        ],
        branchName: `clade/${cladeName.toLowerCase()}`,
        commitMessage: `Add clade: ${cladeName}`,
        prTitle: `Add clade: ${cladeName}`,
        prBody: `Adds ${cladeName} to the taxonomy tree under ${treeParent}.`,
    });
}
